### ISSUE TITLE
Buttons on popup-dialogs not really visible

### ISSUE THREAD

**Issue by banyaszg** [EdgeTX/edgetx#2544]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

The background of the delete model confirmation dialog is the same as the button fill color. So the outline of the button is invisible. It is just a minor inconsistency in appearance.

### Expected Behavior

The dialog background should be different to see the buttons.

### Steps To Reproduce

1. It was tested with default theme.
2. On the model selection page select a model to delete.
3. A confirmation dialog pops up.
4. There is no outline for the non-focused button.

### Version

Nightly (Please give date/commit below)

### Transmitter

Radiomaster TX16S / TX16SMK2

**Comment by raphaelcoeffic** [comment]
@banyaszg I think the issue is that dialogs don't use the regular form background, which make the button have the same color.

**Comment by banyaszg** [comment]
I think so. However I didn't make a full check this time, just ran into the problem and recorded it.
(I tried to setup a model.)

**Comment by raphaelcoeffic** [comment]
> I think so. However I didn't make a full check this time, just ran into the problem and recorded it. (I tried to setup a model.)

You should see it in basically all the pop-up dialogs that have buttons. So I guess the issue should be solved in a generic way by adding the proper background for all of them at once.

**Comment by pfeerick** [comment]
Or change the color of the buttons... (where have I heard that before? :grin:) It is also theme specific - as while this is still not really visible on the actual transmitter, the button is at least a different color to the dialog background.

![image](https://user-images.githubusercontent.com/5500713/195738528-2b9c8ecf-1d07-4d9a-97ab-4c9c95dc390f.png)
![image](https://user-images.githubusercontent.com/5500713/195738579-4aecfdbf-3f4e-4ca8-a6c5-9f4a3c36d312.png)

**Comment by philmoz** [comment]
I think this is fixed in 2.8.1.

**Comment by JimB40** [comment]
Nope.
There are few places in UI where Modal window (pop-up) contains generic data like labels, text or buttons.
In those pop-ups background should be SECONDARY3 not PRIMARY2 

Checked 2.9 nigtly
1. Pop-ups with proper styling

![screenshot_tx16s_23-03-03_11-04-57](https://user-images.githubusercontent.com/46420768/222692704-e3fdff04-4aae-406f-8c2e-b8403d3ec7d4.png)

![screenshot_tx16s_23-03-03_11-05-26](https://user-images.githubusercontent.com/46420768/222692773-bcf86b12-0e35-4b77-8a48-f646c529b39c.png)

2. Pop-ups with wrong styling I have found

![screenshot_tx16s_23-03-03_10-57-27](https://user-images.githubusercontent.com/46420768/222692906-c8155401-391a-4913-a630-5dc48fe2a128.png)

![screenshot_tx16s_23-03-03_10-58-53](https://user-images.githubusercontent.com/46420768/222692932-6bf744f3-c001-4441-bb09-9c0949159339.png)

![screenshot_tx16s_23-03-03_11-02-40](https://user-images.githubusercontent.com/46420768/222692962-71a8dbf8-c526-42d6-ae93-31ae55b8b9fa.png)

![screenshot_tx16s_23-03-03_11-03-34](https://user-images.githubusercontent.com/46420768/222693021-9d5f9340-3c53-43de-be76-d208749b3cd1.png)
