### ISSUE TITLE
EdgeTX Companion 2.7.1 cannot find SD card on Mac OS.

### ISSUE THREAD

**Issue by curuvar** [EdgeTX/edgetx#2568]
I have downloaded the latest EdgeTX companion: Version 2.7.1 (a55aff02).

When I connect my RadioMaster TX16S in USB Storage mode, both the "RM TX16S" firmware drive and the SD card show up on my desktop, but when I try to download from the radio to the Companion application I get the message: "Unable to find radio SD card!" 

I am able to read the SD card directly from Finder, and I can copy the contents of the SD card using the Companion's Synchronize SD function, so I know the USB port and cable are fine.

**Comment by raphaelcoeffic** [comment]
Fixed in #2564

**Comment by magimat** [comment]
I still have this exact problem, even with RC3 of the companion app which renders it useless at this point :(

Does this mean I should try to build the companion app directly form latest sources for now?

How far away is RC4 ?

thanks

**Comment by pfeerick** [comment]
Next few days. 

Companion builds are generated automatically when there are any changes to Companion - you can see the latest builds in the Actions tab at the top of the page. Try https://github.com/EdgeTX/edgetx/actions/runs/3376525087 for the latest 2.8 branch build (scroll to the bottom for the build artefact/download).

**Comment by magimat** [comment]
awesome, it works now. I will be using this build until RC4

thanks
