### ISSUE TITLE
Taranis X9D Plus - startup screen (pre-splash screen!) scrambled / showing 'white noise' or 'afterglow'

### ISSUE THREAD

**Issue by RipperDrone** [EdgeTX/edgetx#4995]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Confirmed with 2 other users on Discord: Taranis X9D Plus (2013) screen is showing 'white noise' screen when powering up, regardless whether splash screen is switched on or off (splash screen will show normally if switched ON, right after the 1-2 secs 'white noise screen'. With some users, it's showing the last screen that was displayed before the transmitter had been switched off last time, instead of the 'white noise' > Looks like screen memory buffer holds random data or last-shown data by the time screen is switched on.

### Expected Behavior

up to v 2.9.3, startup behaviour was normal, no white noise screen shown on power up.

### Steps To Reproduce

1. Flash ETX2.10 to transmitter
2. Switch transmitter on

### Version

Other (Please specify below)

### Transmitter

Other (Please specify below)

### Operating System (OS)

Windows

### OS Version

11 x64

### Anything else?

![image](https://github.com/EdgeTX/edgetx/assets/12601105/a9c2bbea-e572-437a-8d7f-bdc55349bacb)

**Comment by pfeerick** [comment]
It's not just white noise, it can also be last frame that was displayed if
you turn back on again after just turning the transmitter off (shutdown
image). It affects more than taranis also, I have seen that on T20 (i.e.
reverse OLED). As if the display buffer not cleared before/after enabling
display.

**Comment by pfeerick** [comment]
There may have been two separate issues at fault here... X9D and X9D+ would have suffered from the screen not being cleared on startup, hence whatever was in the buffer was being shown, hence "garbage", and by happy coincidence that has been fixed while fixing a completely different issue for the Commando8. The T20, etc should never have been affected by that bug, but currently don't exhibit that behaviour, so will consider that resolved also unless it pops up again.

**Comment by RipperDrone** [comment]
confirmed, resolved on my T16S Plus (2013). Thx again!

**Comment by THEthatdude** [comment]
I'm still getting white snow as well on my X9D+ running 2.10.2. Radio seems to work fine despite it. Custom splash image comes after the snow (about 2 seconds)

**Comment by pfeerick** [comment]
This will be fixed  in 2.10.3 as a side-effect of #5245... X9D/X9D+ weren't doing the screen clear.
