### ISSUE TITLE
Horus X10S channels "twitching" on 2.11.2

### ISSUE THREAD

**Issue by ABLomas** [EdgeTX/edgetx#6404]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

This issue was already discussed in https://github.com/EdgeTX/edgetx/issues/6083 - but it was closed very fast and other comments about testing were ignored (i also asked on discord without reaction).
I cannot re-open issue so i open new - in 2.11.2 problem with channel twitching is still here.
On 2.11.1 i had one channel twitching (disconnecting gimbal does not resolve it - twitching simply migrated to another channel), on 2.11.2 i have all 4 channels (1-4) twitching fast, same on analog debug menu (so this is not script/mix issue).
Rolling back to 2.10 resolves issue completely so this is not hardware fault.

Everything else is exactly as described in https://github.com/EdgeTX/edgetx/issues/6083 - just it was resolved for some, but still here for others.

### Expected Behavior

Have usable transmitter, with stable ch1-ch4 outputs

### Steps To Reproduce

Power on transmitter, observe channel monitor, take look into debug analog menu.

### Version

2.11.2

### Transmitter

FrSky X10 / X10S (ACCST)

**Comment by raphaelcoeffic** [comment]
@ABLomas do you have any way to trace the gimbal signal with a logic analyser? I have no radio where this can be reproduced, so it's gonna be hard to see what's going wrong.

**Comment by ABLomas** [comment]
Yes, i have few LA's (buspirate, Saleae Logic 16 clones), DHO1074 scope and other stuff, not sure how much BW do i need.
What i need to check, signal from hall, or something pre-processed from PCB?

**Comment by 3djc** [comment]
Signal from hall sticks, covering min to max

**Comment by ABLomas** [comment]
I should be on 2.11.2 firmware for this?
With 2.10 pitch stick (others look +/- the same) output (min/max/mid) looks like this:
![Image](https://github.com/user-attachments/assets/d4d9f87e-6717-41a6-91dd-0913673a9551)
![Image](https://github.com/user-attachments/assets/33f0fa19-20a7-4df3-9e9a-c42c57d79ed8)
![Image](https://github.com/user-attachments/assets/56791f3c-a662-4211-a80b-0d8927157bbd)

**Comment by pfeerick** [comment]
> I should be on 2.11.2 firmware for this?

You're measuring the raw output from the gimbal, so I don't think the firmware version being run should matter. Just the timing and the shape of the signal, to ensure there are no issues there, and that it looks like what we expect it to look like.

**Comment by sande005** [comment]
Ran the analogs test on my older X10S-E with 2.11.1 and after 2 hrs, did not see any spikes on screen or in the logs.
Updated that one, **and** my second X10S-E that had been on Ethos until today, to 2.11.2, and after an hour for both, again no spikes.
The mystery deepens.....

**Comment by ABLomas** [comment]
> after 2 hrs, did not see any spikes on screen or in the logs. 

...while on mine outputs twitch every second or so - not even remotely usable.
And yes, signal from hall does not change at all (form and duration stays the same).

I will try to reset radio, recalibrate and make video at evening or tomorrow.

**Comment by 3djc** [comment]
Just a thought: @ABLomas , @sande005 how are your stick names showing in SYS/Hardware analog debug screen ? Are they showing 01...04 or D1....D4 ?

**Comment by sande005** [comment]
For both of my X10S-E's - D1 to D4.  05-09 for the sliders/knobs

**Comment by 3djc** [comment]
> For both of my X10S-E's - D1 to D4. 05-09 for the sliders/knobs

Ok, good, this is what is expected if everything goes well

**Comment by raphaelcoeffic** [comment]
@ABLomas with a Logic 16 clone, you should be able to take a long trace of the gimbal, so we can see if the signal is really 100% steady or if there is anything strange there. If there is nothing to see, then the only thing that could be left would be that *something* is overwriting the memory buffer *somehow* (very odd, other users with the exact same build don't have these issue, AFAIK). Or the timers are behaving strange (that would be really odd, as they seem to work correctly for other users on X10S).

**Comment by ABLomas** [comment]
I left it scope running with trigger on signal width for few hours - not triggered (while axis twiches on menu every second or even faster). So i guess physically everything is OK.
Guess issue affects only X10S, i will try to borrow second one and re-test (but based on comments on other thread issue exists on all X10S non-ACCESS).

I understand that devs do not have access to such hardware - we can do shared session, i have cam, scope (controllable via web, so visible in shared screen) and all soldering tools if needed. Ping me and we arrange session if needed (all time on telegram, but on discord EdgeTX too sometimes, ablomas_abl )

**Comment by DL-JOEY** [comment]
有趣的是，我的第2个通道在上一个版本抽搐，最新版本反而没有，我当时还以为已经解决了这个问题，哈哈哈

**Comment by davidabevan** [comment]
I also have this issue with my x10s,  was fine on v2.8.4 will revert.
Havent any diagnostic here but just advising of duplicate issue .
Thanks

**Comment by davidabevan** [comment]
i flashed bacwards each version until gimbals normal.
noted on 2.11.1 just elevator gimbal shows this fast fluctuation ,info  radio mode 2 aetr config.
centurion 2,10.6 no issues.
seems that something in jolly mon branch has broken hall gimbals.
my radio is the old horus x10s very solid radio i keep going back to.
Hope this info helps

**Comment by j-brubaker** [comment]
I have two Horus X10S (not Express) and both exhibit the extremely rapid channel value fluctuation on 2.11.2.

**Comment by raphaelcoeffic** [comment]
If one of you could send me one of the problematic gimbals, I do have a X10 I could mount that gimbals into and try. Best would be of course both gimbals (less code changes necessary to test).

Otherwise, could someone confirm these are the gimbals mounted into your X10S?
- https://www.engelmt.de/mtfrsky-transmitters-und-accessories/accessories/horus-x10-series/horus-x10_x10s-mc12p-gimbal

Additionally, if the gimbals cannot be sent, a logic analyser (preferably using [Logic2](https://www.saleae.com/pages/downloads)) trace during many minutes would already help, as well as some notes of the time points where twitching happened.

**Comment by davidabevan** [comment]
Ref.
f one of you could send me one of the problematic gimbals, I do have a X10
I could mount that gimbals into and try. Best would be of course both
gimbals (less code changes necessary to test).

Otherwise, could someone confirm these are the gimbals mounted into your
X10S?

Hi Raphael yes I believe these are fitted.
Please read previous on thread. Older edge tx version doesn't cause this
behaviour.
I don't have logic analysis here.
I understand it's a bit tricky to nail down the culprit. I have reverted to
the old version I was running gimbals perfect.
Thanks

**Comment by raphaelcoeffic** [comment]
> Older edgetx version doesn't cause this behaviour.

We've established that already, no need to repeat it. There are however no code changes that could explain anything like that.
Without being able to reproduce it myself, or at least see what is happening, I have no idea how I can help.

**Comment by ABLomas** [comment]
> If one of you could send me one of the problematic gimbals, I do have a X10 I could mount that gimbals into and try. Best would be of course both gimbals (less code changes necessary to test).

There's no twitching on gimbal itself, signal is stable and without changes, i alread checked. Because twitching happens every second - it should be visible immediately, while scope with trigger (selae logic, bus pirate, sigrok whatever) shows no difference in signal at the same time.

So i doubt "sending gimbals" would help in any way, sending entire radio is different thing, but before going this route i offered easier way - remote debugging (i got all tools needed i think), but nobody interested and i'm not ready to do deep dive into code yet (maybe at winter time, now radio is used for flying...)

**Comment by gagarinlg** [comment]
Can you please try the next nightly?
We merged a fix for a similar issue in H7 radios today.

**Comment by j-brubaker** [comment]
> Can you please try the next nightly? We merged a fix for a similar issue in H7 radios today.

I just flashed the nightly x10-e427c30.bin and the issue persists.

Flashed back to 2.10.6 and the analog debug screen shows no twitching.

**Comment by davidabevan** [comment]
Yes Problem persists with me also with nightly thanks for positive suggestion, 
Ive made a short vid clip of debug screen maybe helpful,
https://www.youtube.com/shorts/pCUqPtLStpE

**Comment by raphaelcoeffic** [comment]
@davidabevan what I see on your video is that the gimbals in "debug analog" are not shown as `D1` to `D4`, but `01` to `04`, which means that the gimbals are not detected as PWM gimbals, and used as analog gimbals. In that case, the explanation is simple: it cannot work and whatever you do with the sticks, it will just show bullshit values changing fast from one extreme to the other.

What is also clear: the PWM gimbal code does not permit values below `80` or higher than `3820` (non-inverted channels, on the X10 this means `D1` and `D3`). On inverted channels (`D2` and `D4`), the values are then `4015` (`4095 - 80`) and `275` (`4095 - 3820`).

So if you see any values outside the previously mentioned boundaries, you can be sure that these values have not been written by the PWM gimbal driver.

For reference (`sticks_pwm_driver.cpp`, lines 180 to 183):
```c
        if (value > PWM_MIN_PULSE && value < PWM_MAX_PULSE) {
          adcValues[i] = input.inverted ? ADC_INVERT_VALUE(value) : value;
          _pwm_samples[i]++;
        }
```

Let's make sure we're really testing the PWM gimbal driver and force its activation. This firmware is based on v2.11.3 and adds **forced PWM gimbals**. It will not work on anything else but a X10S (ACCST) with MC12P gimbals.

[X10S-v2.11.3-forced-pwm-gimbals.zip](https://github.com/user-attachments/files/21966399/X10S-v2.11.3-forced-pwm-gimbals.zip)

Here is the diff against `v2.11.3` release tag:
```diff
diff --git a/radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp b/radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
index bca56f4e8a..d00ef27ad6 100644
--- a/radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
+++ b/radio/src/targets/common/arm/stm32/sticks_pwm_driver.cpp
@@ -103,6 +103,10 @@ bool sticks_pwm_detect(const stick_pwm_timer_t* timer,
   memset(&_pwm_samples, 0, sizeof(_pwm_samples));
   sticks_pwm_init(timer);
 
+  // force PWM gimbals
+  stm32_hal_set_inputs_mask(0xF);
+  return true;
+
   uint32_t timeout = timersGetMsTick() + PWM_DETECT_MS;
   while (timersGetMsTick() - timeout > 0) {}
 
```

**Comment by davidabevan** [comment]
I will test code later today thanks.
What I am not understanding now. Is why if I flash previously mentioned
firmware without making any changes. I have perfectly working gimbal and no
issues calibrating.
I think you may be on the right track that's why I posted all the different
debug screens.
Will get back to you later.
Thanks

**Comment by raphaelcoeffic** [comment]
> if I flash previously mentioned firmware

What is *"previously mentioned firmware"*? You will notice that I took great care of being precise. I expect the same from everyone else.

**Comment by davidabevan** [comment]
V2.10.6
Anything after shows this gimbal issue thanks

**Comment by davidabevan** [comment]
Please try and be kind. More forgiving
We are not all programmers and don't know the etiquette. I am trying to be
brief and polite trying to help solve issues
Thankyou

**Comment by raphaelcoeffic** [comment]
> We are not all programmers and don't know the etiquette

There is no need to be a programmer for being precise. It is an important part of human communication to avoid misunderstandings.

> What I am not understanding now. Is why if I flash previously mentioned firmware without making any changes.

Here is a small summary of the relevant changes (PWM gimbal driver / board initialisation):

- between `v2.10.6` and `v2.11.0`:
    - PWM gimbals driver: **none**.
    - Board initialisation: **close to none** (PWM gimbals are initialised at the same moment during boot; slight changes at other places in board init).
 
- between `v2.11.0` and `v2.11.1`: improved PWM gimbal detection (see #6161 for details).
- between `v2.11.1` and `v2.11.2`: verify PWM gimbal pulse length (see #6283 for details).

**Comment by 3djc** [comment]
> V2.10.6
> Anything after shows this gimbal issue thanks
> […](#)

That's typically why beyond usual precision is required. It is unclear here if https://github.com/user-attachments/files/21966399/X10S-v2.11.3-forced-pwm-gimbals.zip is part of "anything after" or you meant whithout saying it "official releases"

**Comment by j-brubaker** [comment]
I flashed "X10S-v2.11.3-forced-pwm-gimbals" to my first X10S that had been flashed back to 2.10.6 after trying the nightly last night.  The channel jitter appears gone in the analog debug screen and the gimbals are listed as "D1-D4."

On my second X10S which had the issue, I verified that on 2.11.2, it showed "01-04" on the analog debug screen. I then flashed it to the provided "X10S-v2.11.3-forced-pwm-gimbals" firmware.  Analog debug screen now shows "D1-D4" and the channel jitter is gone on my second unit as well.

**Comment by raphaelcoeffic** [comment]
@j-brubaker thx a lot for rapid testing! This shows a clear evidence that, at least your particular case, we are dealing with a detection issue.

The question that obviously follows is why the current detection does not work.

Looking at the different code changes between version as listed (see https://github.com/EdgeTX/edgetx/issues/6404#issuecomment-3219802900), it could be a subtle timing issue and we're potentially very close, but not close enough to achieve a proper decision in all cases (it appears to work with many X10S, but not with all of them).

Ideally, @ABLomas could provide us with a logic trace showing the gimbal sensors' signal as well as other (to be determined) signals so we can assert when exactly during boot the signal becomes stable enough so it can be reliably detected.

ATM, the boot sequence must be able to safely assert which type of signal we have (serial, PWM or just analog voltage), to avoid having to produce a different firmware for each radio variant and allow customisation (after sale use of MC12P gimbals, FlySky gimbals, or others).

By the way, I made a simulation rig for my X10, thus allowing me to generate different types of PWM signals directly connected to the board. Given a proper trace, I should be able to reliably test this.

**Comment by raphaelcoeffic** [comment]
Testing with @ABLomas, he discovered that the gimbal detection was dependent on the state of the throttle gimbal. Raising it a bit made the gimbal detection work. So here is a firmware with raised limits that should work better:

[X10S-40-4000.zip](https://github.com/user-attachments/files/21973214/X10S-40-4000.zip)

**Comment by j-brubaker** [comment]
> So here is a firmware with raised limits that should work better:
> 
> [X10S-40-4000.zip](https://github.com/user-attachments/files/21973214/X10S-40-4000.zip)

Flashed this and can confirm that the gimbals are detected correctly (i.e. shows "D1-D4" in Analog Debug screen) and there is no jitter on the channel values.  Only tested on one of my X10S at the moment.

**Comment by robustini** [comment]
This issue was already discussed also [here](https://github.com/EdgeTX/edgetx/issues/5613).
I reported this issue a long time ago.
I also have an X12S, and it doesn't do that on that one.
Tomorrow I'll try again with the latest 2.11.x firmware.

**Comment by raphaelcoeffic** [comment]
> Tomorrow I'll try again with the latest 2.11.x firmware.

It is not yet in any release. If you want to test, please use the firmware from https://github.com/EdgeTX/edgetx/pull/6550 (PR based on 2.11.3).

**Comment by wucke13** [comment]
I did observe the erratic behavior (the four stick channels jump quickly between 0 and 2048) on a X10S (non-access) with v2.11.3 as well, but only when the following is all true

- radio is booted while its cold, less than 5 °C
- throttle is at minimum (I fly Mode 2/Mode 4, so throttle is left).

I believe, that there is a slight anti-proportional relation between intensity of the B-field sensed by the hall sensors and the temperature, so by chilling the hall sensors (and/or the magnets?) the sensed position wanders of ever so slightly further towards the extreme. Now, when the PWM signal is really really close to a logical 0 (stick in lowermost position), it becomes indistinguishable to an analog signal close to 0, thus the radio detects analog sticks (despite them being PWM) and all channel jerk from 0 to 2048 (since PWM is a rectangular signal, after all).

I got kind of scared in the beginning fearing I have to get a new radio, because obviously having these wild jumps in the stick values is an unacceptable failure condition during flight, but now that I understood the mechanism its easy enough to avoid, just turn up the throttle during boot-up.

I know the issue is already closed, I just wanted to document my observations in case anyone else stumbles into this; while the root cause seems to be already discussed [here](https://github.com/EdgeTX/edgetx/issues/6404#issuecomment-3219672970) (PWM gimbals are detected as analog gimbals), the possible connection to the combination of stick position during boot-up and weather conditions I observed was not yet documented here.
